<?php

/**
 * @file
 * Contains simple_sharethis.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_sharethis_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_sharethis module.
    case 'help.page.simple_sharethis':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple ShareThis - Custom Block Drupal 8.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function simple_sharethis_theme() {
  return [
    'theme_simple_share_this_block' => [
      'template' => 'simple_sharethis',
      'variables' => [],
    ],
  ];
}
